### ISSUE TITLE
AttributeError: 'FilesPane' object has no attribute '_FilesPane__download_progress_pre'

### ISSUE THREAD

**Issue by HashimJVZ** [sivasankarankb/pyfileshare#1]
I just downloaded and run the server and gui file (on the same machine), and encountered this issue.
I was not running the client program, don't know if that the issue.
was running on windows 11

```
$ python pyfs-gui.py
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\hashi\AppData\Local\Programs\Python\Python310\lib\tkinter\__init__.py", line 1921, in __call__
    return self.func(*args)
  File "C:\Users\hashi\Downloads\pyfileshare-master\pyfileshare-master\pyfs-gui.py", line 233, in __filelist_go
    self.connect_to(address)
  File "C:\Users\hashi\Downloads\pyfileshare-master\pyfileshare-master\pyfs-gui.py", line 156, in connect_to
    self.__client.getfile_monitor_silence(self.__download_progress_pre)
AttributeError: 'FilesPane' object has no attribute '_FilesPane__download_progress_pre'
```

**Comment by sivasankarankb** [comment]
I'm glad you are trying this app. The latest commit is pretty messy.

Just do:

git reset HEAD~1
git restore "*"

This should get you to the previous, stable commit.

I'll be sure to add a stable branch to this repo ASAP.

Cheers! 😁

Please reply even if that fixed it.

**Comment by sivasankarankb** [comment]
You can now get the latest stable version from the releases page.

**Comment by sivasankarankb** [comment]
There's nothing more to do here. :grin:
